app = "linear-algebra-calculator"
primary_region = "fra"  # You can change this to a region closer to you

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services.concurrency]
  hard_limit = 25
  soft_limit = 20

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static"

[mounts]
  source="linalgdata"
  destination="/data"
