app = 'linear-algebra-calculator'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

[checks]
  [checks.health]
    port = 8501
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/_stcore/health"

[[mounts]]
  source = 'linalgdata'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'